
<% require "dotenv"; Dotenv.load(".env") %>
service: music_share_api
image: <%= ENV.fetch("DOCKER_USERNAME") %>/music_share_api
# Only include your actual server IP
servers:
  web:
    - <%= ENV['SERVER_IP'] %>
registry:
  username: ${DOCKER_USERNAME}
  password: ${KAMAL_REGISTRY_PASSWORD}
env:
  secret:
    - RAILS_MASTER_KEY
    - SPOTIFY_CLIENT_ID
    - SPOTIFY_CLIENT_SECRET
  clear:
    RAILS_ENV: production

    DATABASE_USERNAME:  <%= ENV['DATABASE_USERNAME'] %>
    DATABASE_PASSWORD: <%= ENV['DATABASE_PASSWORD'] %>
    DATABASE_HOST: music_share_api-db
    DATABASE_PORT: <%= ENV['DATABASE_PORT'] %>
ssh:
  user: deploy
  key_data: [<%= ENV['SSH_PRIVATE_KEY'].inspect %>]

volumes:
  - 'music_share_api_storage:/rails/storage'

builder:
  arch: amd64

# Configure PostgreSQL as an accessory
accessories:
  db:
    image: postgres:15

    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>
    env:
      POSTGRES_USER: <%= ENV['DATABASE_USERNAME'] %>
      POSTGRES_PASSWORD: <%= ENV['DATABASE_PASSWORD'] %>
      POSTGRES_DB: music_share_api_production
    volumes:
      - data:/var/lib/postgresql/data

proxy:
  healthcheck:
    interval: 10
    timeout: 15
